//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDemo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbSalesInvoiceItem
    {
        public int InvoiceItemId { get; set; }
        public int InvoiceId { get; set; }
        public int ItemId { get; set; }
        public decimal SalesPrice { get; set; }
        public int Qty { get; set; }
        public string Notes { get; set; }
    
        public virtual TbItem TbItem { get; set; }
        public virtual TbSalesInvoice TbSalesInvoice { get; set; }
    }
}
